---
- hosts: all
  become: yes
  remote_user: vaultadmin
  become_user: root
  tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

- hosts: all
  become: yes
  remote_user: vaultadmin
  become_user: root
  roles:
     - role_vault_install
...